version: 2.1

orbs:
  gem: goldstar/publish-gem@1.3.0

workflows:
  main:
    jobs:
      - gem/test:
          executor_type:
            name: gem/ruby
            exec_ruby_version: 2.6.7-node-browsers
      - gem/build-and-deploy:
          executor_type:
            name: gem/ruby
            exec_ruby_version: 2.6.7-node-browsers
          context: packagecloud
          requires:
            - gem/test
          filters:
            branches:
              only: master
          packagecloud-repo: goldstar/production

